name: docs
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install uv
      - run: uv sync
      - run: uv run python scripts/mkdocs_generate_reference.py
      - run: uv run mkdocs gh-deploy --force
