name: docs
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          pip install uv
          uv sync
      - name: Generate API reference docs
        run: |
          uv run python scripts/mkdocs_generate_reference.py
      - name: Deploy to GitHub Pages
        run: uv run mkdocs gh-deploy --force
