name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "**.py"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        run: uv python install
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run tests
        env:
          ZENDRIVER_TEST_BROWSERS: "headless"
        run: /bin/bash ./scripts/test.sh
